language: node_js
node_js:
  - '0.10'
before_script:
  - npm install -g grunt-cli
deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app:
    master: alm-course-2016-staging
    production: alm-course-2016-production
    /^feature.*$/: alm-course-2016-dev
    dev: alm-course-2016-dev